# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## header - reject

header:
    reject: true

## menu
menu:
- page: home
  url: /
  icon: fa-home
- page: 前端
  url: /categories/前端/
  icon: fa-chrome
- page: 工具
  url: /categories/工具/
  icon: fa-wrench
- page: 时间轴
  url: /archives/
  icon: fa-clock-o
- page: 要闻
  url: /categories/要闻/
  icon: fa-google-wallet
- page: 日记
  url: /categories/日记/
  icon: fa-book
- page: 404
  url: /404.html
  icon: fa-bug

## favicon
favicon: /favicon.ico

## Feed
rss: /atom.xml

## Carousel
carousel:
  carousel: false
  img: './img/head-img.jpg'
  url: 'https://algate.github.io'

# 各个小工具的设置

## widgets
widgets:
  - search
  - notification
  - social
  - category
  - archive
  - tagcloud
  - friends
  - stick


## 搜索
jsonContent:
  meta: true
  searchLocal: true
  searchGoogle: false
  posts:
    title: true
    text: true
    content: true
    categories: false
    tags: false

## 网站公告设置
notification:
    |-
    <p>
        微信订阅号：<img src="/img/wx-onion.png" /> <br/>
        原博客地址(旧文章)：<a href="https://algate.github.io/hexo.pure" title="algate" target="_blank">网站主页</a> <br/>
        VUE地址：<a href="https://algate.github.io/onions.vuecli3" title="vue" target="_blank">VUECLI3项目预览</a> <br/>
        React地址：<a href="https://algate.github.io/onions.com" title="react" target="_blank">React项目预览</a> <br/>
    </p>
    <hr/>
    <h3>欢迎购买我的广告位，谢谢您的支持！</h3>
    <p>
        <a href="javascript:void(0);" target="_blank">
            <img src="/img/sale.png" />
        </a>
    </p>

## 社交设置
social:
 - name: Github
   icon: git
   href: //github.com/algate
 - name: 邮箱
   icon: envelope-o
   href: mailto:algate@foxmail.com
 - name: 联系QQ
   icon: qq
   href: http://wpa.qq.com/msgrd?v=3&uin=361593833&site=qq&menu=yes
 - name: 微信
   icon: weixin
   href:
   src: /img/weixinconcat.png
 - name: 加入QQ群
   icon: group
   href: http://shang.qq.com/wpa/qunwpa?idkey=ee9ad994222792f08ab657adb97d6d8dc4cff89a6a0a6a35ae9de4cac473c552
 - name: RSS
   icon: feed
   href: /atom.xml

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   format: 'YYYY年MM月'
   show_count: true
   order: -1

## 标签云设置
tagcloud:
  tag3d: true
  textColour: '#444'
  outlineMethod: 'block'
  outlineColour: '#FFDAB9'
  interval: 30
  freezeActive: true
  frontSelect: true
  reverse: true
  wheelZoom: true

## 友链设置
links:
  - Hexo官网: https://hexo.io/zh-cn/
  - TTF的家园: http://www.ttfde.top


# 主题自定义个性化配置

## 网站宣传语
branding: 不要跟我谈理想，我的理想是不工作
oldbranding:

## 设置banner背景图片./img/banner.jpg
banner:
    img:

## 首页列表底部面板
homePanel: true

## 缩略图自定义随机图片
defaultImgs:
  -

## 截取文章首页描述字数
excerptLength: 120

## 是否开启文章目录
toc: true

## 代码高亮配置
highlightTheme:

## bootstrap配置
bootstrap:

## ICON配置
fontAwesome:

## 文章过期提醒功能
warning:
  days: 300
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 文章内声明  -  use
declaration:
  enable: true
  title: '转载声明'
  tip: |-
      商业转载请联系作者获得授权,非商业转载请注明出处 © <a href="" target="_blank">Onions</a>

## 文章打赏  -  use
reward:
  alipay: '/img/alipayimg.png'
  wepay: '/img/weipayimg.png'
  tip: 赞赏是不耍流氓的鼓励

## 主题评论

## Valine评论 (LeaCloud)  - use
valine:
   enable: true
   appId: XCBkrMT2cT5gHnAV3uKwy2Eo-gzGzoHsz
   appKey: bX6iJOMctdSEGOXysJloaoGN
   placeholder: 不要和我谈理想，我的理想是不上班！
   notify: false
   verify: false
   avatar: onions
   meta: nick,mail
   pageSize: 10

### 畅言评论(需要ICP备案)
changyan:
  enable: false
  appid:
  conf:

### 来必力
livere:
  enable: false
  livere_uid: MTAyMC8zNDMxNS8xMDg1Mg==

## Gitalk评论
gitalk:
   enable: false
   clientID: 0b0d43a49adc0200ac23
   clientSecret: 82553f5ed0d11dc2792158cf476aa731664467ca
   repo: algate.github.io
   owner:
   admin:
   perPage:
   id: algate

### Disqus评论
disqus:
  enable: false
  shortname: snippet
  count: false

### gitment评论(长期不更新，不建议使用)
gitment:
  enable: false
  owner:
  repo:
  client_id:
  client_secret:
  perPage: 10

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id: 1966422


## 网站访客统计 copyright - busuanzi  -  use
visit_counter:
   site: true
   page: false

## 网站访问统计分析

### 网盟CNZZ统计  - use
cnzz_analytics: 1276282118

### 百度统计 - use
baidu_analytics: 617bf75bfd954382202927d87bf48f13

### 谷歌统计
google_analytics:

### 腾讯分析 - use (http请求被拒绝，暂时无法使用)
# tencent_analytics: 66183388
tencent_analytics:

### 百度站点认证
baidu_site_verification:

### 百度自动推送
baidu_push: false

#网站主题配置
since: 2016-2019
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.2.1
